export const EPLOY_STUB_JOB_ROLE = {
  JobRoleId: 101,
  Title: "Senior Software Engineer",
  Reference: "ENG-2026-001",
  Active: true,
  ParentJobRole: { Id: 10, Url: "https://api.eploy.net/api/v3/jobRoles/10" },
  Companies: [{ Id: 1, Url: "https://api.eploy.net/api/v3/companies/1" }],
  VacancyTemplates: [],
  Position: {
    Id: "POS-999",
    Description: "Backend API development in Node.js",
    Reference: "REF-999",
    ArchiveDate: null,
    ParentId: null,
    OptionType: { Id: 1, Url: "", Description: "Full Time", Type: "Duration" }
  },
  Creator: { Id: 1, Url: "" },
  Modifier: { Id: 1, Url: "" },
  CreationDate: "2026-01-15T08:00:00.000Z",
  ModificationDate: "2026-04-01T10:00:00.000Z",
  QuestionFields: []
};

export const EPLOY_STUB_JOB_ROLES_SEARCH = {
  Records: [
    EPLOY_STUB_JOB_ROLE,
    {
      JobRoleId: 102,
      Title: "Product Manager",
      Reference: "PROD-2026-002",
      Active: true,
      ParentJobRole: { Id: 11, Url: "https://api.eploy.net/api/v3/jobRoles/11" },
      Companies: [{ Id: 1, Url: "https://api.eploy.net/api/v3/companies/1" }],
      VacancyTemplates: [],
      Position: {
        Id: "POS-998",
        Description: "Lead the roadmap for the new Herdhunter product",
        Reference: "REF-998",
        ArchiveDate: null,
        ParentId: null,
        OptionType: { Id: 1, Url: "", Description: "Full Time", Type: "Duration" }
      },
      Creator: { Id: 1, Url: "" },
      Modifier: { Id: 1, Url: "" },
      CreationDate: "2026-02-10T09:30:00.000Z",
      ModificationDate: "2026-03-20T14:15:00.000Z",
      QuestionFields: []
    }
  ],
  TotalRecords: 2,
  CurrentPage: 1,
  TotalPages: 1
};

export const EPLOY_STUB_CV_SEARCH = {
  Records: [
    {
      StoredFileId: 5001,
      StoredFileType: {
        Id: "CV",
        Description: "Curriculum Vitae",
        Reference: "CV-DOC",
        ArchiveDate: null,
        ParentId: null,
        OptionType: { Id: 1, Url: "", Description: "Document", Type: "FileType" }
      },
      FileName: "JohnDoe_CV_2026",
      FileExtension: ".pdf",
      FileSize: 1048576,
      DateCreated: "2026-04-05T08:28:56.631Z",
      DateLastAccessed: "2026-04-06T10:15:00.000Z",
      DateLastModified: "2026-04-05T08:28:56.631Z",
      Download: "https://api.eploy.net/api/v3/files/cv/5001/download",
      Candidate: { Id: 9001, Url: "https://api.eploy.net/api/v3/candidates/9001" },
      Creator: { Id: 1, Url: "" },
      Modifier: { Id: 1, Url: "" },
      CreationDate: "2026-04-05T08:28:56.631Z",
      ModificationDate: "2026-04-05T08:28:56.631Z",
      QuestionFields: []
    }
  ],
  TotalRecords: 1,
  CurrentPage: 1,
  TotalPages: 1
};

export const EPLOY_STUB_CV_DOWNLOAD = {
  StoredFileId: 5001,
  StoredFileType: {
    Id: "CV",
    Description: "Curriculum Vitae",
    Reference: "CV-DOC",
    ArchiveDate: null,
    ParentId: null,
    OptionType: { Id: 1, Url: "", Description: "Document", Type: "FileType" }
  },
  FileName: "JohnDoe_CV_2026",
  FileExtension: ".pdf",
  FileSize: 1048576,
  DateCreated: "2026-04-05T08:28:56.631Z",
  DateLastAccessed: "2026-04-06T10:15:00.000Z",
  DateLastModified: "2026-04-05T08:28:56.631Z",
  Download: "https://api.eploy.net/api/v3/files/cv/5001/download",
  Candidate: { Id: 9001, Url: "https://api.eploy.net/api/v3/candidates/9001" },
  Creator: { Id: 1, Url: "" },
  Modifier: { Id: 1, Url: "" },
  CreationDate: "2026-04-05T08:28:56.631Z",
  ModificationDate: "2026-04-05T08:28:56.631Z",
  QuestionFields: []
};

// Also usually contains base64 encoded file content or acts as a redirect in actual Eploy
// EPLOY_STUB_CV_DOWNLOAD does not contain actual bytes in standard JSON GET unless encoded into a specific field like "FileData"
// Assuming Standard Eploy returns JSON with a separate stream/URL, but we provide the JSON wrapper here.

export const EPLOY_STUB_CANDIDATE = {
  CandidateId: 9001,
  Import: "WebForm",
  Reference: "CAND-2026-9001",
  Websites: [],
  City: { Id: "CITY-LOND", Description: "London", Reference: "LON", ArchiveDate: null, ParentId: null, OptionType: null },
  Company: null,
  Contact: null,
  Users: [],
  Vendors: [],
  NINumber: "AB123456C",
  Title: { Id: "TITLE-MR", Description: "Mr", Reference: "MR", ArchiveDate: null, ParentId: null, OptionType: null },
  FirstName: "John",
  MiddleName: "Edward",
  Surname: "Doe",
  MaidenName: null,
  Salutation: "John",
  VocationalGuidance: false,
  ChildrenAges: null,
  Status: { Id: "STAT-ACTIVE", Description: "Active", Reference: "ACT", ArchiveDate: null, ParentId: null, OptionType: null },
  Address: {
    Address1: "123 Tech Street",
    Address2: "Silicon Roundabout",
    Address3: null,
    Town: "London",
    County: "Greater London",
    Country: { Id: "UK", Description: "United Kingdom", Reference: "UK", ArchiveDate: null, ParentId: null, OptionType: null },
    PostCode: "EC1V 9HX",
    AddressStartDate: "2020-01-01T00:00:00.000Z",
    AddressEndDate: null
  },
  Telephone: "020 7946 0000",
  WorkTelephone: null,
  WorkTelephoneExtension: null,
  Telephone2: null,
  Fax: null,
  Mobile: "07700 900123",
  Email: "john.doe.tester@example.com",
  Email2: null,
  WebsiteAddress: "https://linkedin.com/in/johndoe",
  DateOfBirth: "1990-05-15T00:00:00.000Z",
  Gender: { Id: "MALE", Description: "Male", Reference: "M", ArchiveDate: null, ParentId: null, OptionType: null },
  Nationality: { Id: "BRITISH", Description: "British", Reference: "GBR", ArchiveDate: null, ParentId: null, OptionType: null },
  Nationality2: null,
  EthnicOrigin: null,
  Religion: null,
  ReligionOther: null,
  Sexuality: null,
  Disabilities: false,
  DisabilitiesDescription: null,
  DisabilityNumber: null,
  DisabilitiesEffect: false,
  SpecialArrangements: null,
  PresentHealth: "Good",
  CriminalRecord: false,
  CriminalRecordDescription: null,
  CRBDateSent: null,
  CRBDateReceived: null,
  WorkPermit: false,
  WorkPermitType: null,
  WorkPermitCountry: null,
  WorkPermitStatus: null,
  WorkPermitNumber: null,
  WorkPermitExpiryDate: null,
  WorkPermitVerificationDate: null,
  WorkPermitVerifier: null,
  WorkPermitComments: null,
  DrivingLicence: true,
  ProvisionalLicence: false,
  DatePassedTest: "2010-06-01T00:00:00.000Z",
  DrivingLicencePoints: 0,
  OwnACar: false,
  Declaration: true,
  VerificationDate: "2026-04-01T00:00:00.000Z",
  RegularContact: true,
  RegularContactDate: "2026-04-07T00:00:00.000Z",
  OccasionalContact: false,
  OccasionalContactDate: null,
  ThirdPartyContact: false,
  ThirdPartyContactDate: null,
  EthnicOriginOther: null,
  CandidateLevel: 3,
  CurrentEmployer: "Tech Corp Inc.",
  BusinessArea: null,
  CurrentPosition: { Id: "POS-SE", Description: "Software Engineer", Reference: "SE", ArchiveDate: null, ParentId: null, OptionType: null },
  PreferredPosition1: { Id: "POS-SSE", Description: "Senior Software Engineer", Reference: "SSE", ArchiveDate: null, ParentId: null, OptionType: null },
  PreferredPosition1Other: null,
  PreferredPosition2: { Id: "POS-MGR", Description: "Engineering Manager", Reference: "EM", ArchiveDate: null, ParentId: null, OptionType: null },
  PreferredPosition2Other: null,
  PreferredPosition3: null,
  PreferredPosition3Other: null,
  PreferredJobTitle1: "Senior Developer",
  PreferredIndustry1: { Id: "IND-TECH", Description: "Technology", Reference: "TECH", ArchiveDate: null, ParentId: null, OptionType: null },
  PreferredIndustry1Other: null,
  PreferredIndustry2: null,
  PreferredIndustry2Other: null,
  PreferredIndustry3: null,
  PreferredIndustry3Other: null,
  PreferredLocation1: { Id: "CITY-LOND", Description: "London", Reference: "LON", ArchiveDate: null, ParentId: null, OptionType: null },
  PreferredLocation2: { Id: "REMOTE", Description: "Remote", Reference: "REM", ArchiveDate: null, ParentId: null, OptionType: null },
  PreferredLocation3: null,
  Currency: { Id: "GBP", Description: "British Pound", Reference: "GBP", ArchiveDate: null, ParentId: null, OptionType: null },
  CurrentRemuneration: "75000",
  CurrentBonus: "5000",
  RemunerationRequired: "90000",
  CurrentBenefits: "Pension, Health Insurance",
  MinimumSalary: 85000,
  MinimumRate: { MinimumRate: 400, MinimumRateInterval: { Id: "DAY", Description: "Per Day", Reference: "DAY", ArchiveDate: null, ParentId: null, OptionType: null } },
  NoticeRequired: "3 Months",
  Keywords: "Node.js, TypeScript, React, Postgres",
  Comments: "Looking for a lead role.",
  PreferredJobDescription1: "Backend heavy role with architecture responsibilities",
  ReasonForLooking: "Career progression",
  IncludeCompanies: "Startups, Mid-size tech",
  ExcludedCompanies: "Banking",
  PreferredVacancyTypes: [],
  PreferredSubjects: [],
  LeisureInterests: "Climbing, Coding, Read",
  SpecialAptitudes: "Hackathon winner",
  TechnicalSkills: "TypeScript, Node, React, Next.js, Postgres",
  WillRelocate: false,
  DistanceToTravel: "10 miles",
  AvailableFromDate: "2026-07-01T00:00:00.000Z",
  AvailableToDate: null,
  Source: "LinkedIn",
  InfluenceToApply: null,
  InfluenceToApplyDetail: null,
  InfluenceToApplyDate: null,
  InfluenceToApplyDescription: null,
  EmploymentStatus: { Id: "EMP-PERM", Description: "Permanent", Reference: "PERM", ArchiveDate: null, ParentId: null, OptionType: null },
  CandidateEmploymentStatus: null,
  ContactByType: null,
  ContactReferences: true,
  EducationPoints: 100,
  IsEmployee: false,
  IsPreviousEmployee: false,
  WorkExperience: 5,
  CurrentPositionOther: null,
  CandidateAddresses: "[]",
  CandidateBank: "{}",
  CandidateEmployment: "[]",
  CandidateExams: "[]",
  CandidateLanguages: "[]",
  CandidatePreferences: "{}",
  CandidateQualifications: "[]",
  CandidateReferences: "[]",
  CandidateSchools: "[]",
  CandidateUniversity: "[]",
  SystemLanguage: null,
  Questions: "[]",
  Creator: { Id: 1, Url: "" },
  Modifier: { Id: 1, Url: "" },
  CreationDate: "2026-04-07T08:30:37.348Z",
  ModificationDate: "2026-04-07T08:30:37.348Z",
  QuestionFields: []
};

export const EPLOY_STUB_ERROR = {
  error_message: "Resource not found or unauthorized access."
};
